vj_rating/main/models.py
import json
from datetime import datetime

from sqlalchemy.ext.associationproxy import association_proxy

from .. import db
from ..utils.rating_calculator import CodeforcesCalculator


class Contestant(db.Model):
    __tablename__ = 'contestants'
    user_id = db.Column(db.Integer, db.ForeignKey(
        'users.id'), primary_key=True)
    contest_id = db.Column(db.Integer, db.ForeignKey(
        'contests.id'), primary_key=True)
    before_rating = db.Column(db.Integer, default=None)
    after_rating = db.Column(db.Integer, default=1500)
    rank = db.Column(db.Integer)
    solved = db.Column(db.Integer)
    penalty = db.Column(db.Integer)
    user = db.relationship('User', back_populates='as_contestants')
    contest = db.relationship('Contest', back_populates='contestants')

    def as_dict(self):
        return {
            'name': self.contest.name,
            'time': self.contest.start_time.strftime('%Y-%m-%dT%H:%M:%S') + 'Z',
            'rating': self.after_rating
        }

    def __repr__(self):
        return '<Contestant %d %d>' % (self.user_id, self.after_rating)


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True, nullable=False)
    nickname = db.Column(db.String(64), unique=True)
    rank = db.Column(db.Integer, default=None)
    rating = db.Column(db.Integer, default=None)
    as_contestants = db.relationship(
        'Contestant', back_populates='user')
    contests = association_proxy('as_contestants', 'contest')

    @property
    def sorted_contestants(self):
        return sorted(self.as_contestants, key=lambda x: x.contest.start_time)

    def gen_contest_list(self):
        return json.dumps(list(map(lambda x: x.as_dict(), self.sorted_contestants)))


class Contest(db.Model):
    __tablename__ = 'contests'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    start_time = db.Column(db.DateTime(), default=datetime.utcnow())
    end_time = db.Column(db.DateTime(), default=datetime.utcnow())
    participant_count = db.Column(db.Integer)
    last_calculate_rating_time = db.Column(db.DateTime, default=None)
    html = db.Column(db.Text)
    users = association_proxy('contestants', 'user')
    contestants = db.relationship(
        'Contestant', back_populates='contest', order_by=Contestant.rank)

    def calculate_rating(self):
        CodeforcesCalculator.calculate_rating(self.contestants)
        db.session.add_all(self.contestants)
        db.session.add_all(self.users)
        self.last_calculate_rating_time = datetime.utcnow()
        self.participant_count = len(self.contestants)
        db.session.add(self)
        db.session.commit()

vj_rating/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates')

from . import views

vj_rating/main/views.py
from flask import render_template
from sqlalchemy import desc

from . import bp
from .models import Contest, User

@bp.route('/')
def index():
    return render_template('main/index.html')

@bp.route('/rank_list/')
def rank_list():
    users = User.query.order_by(desc(User.rating)).all()
    return render_template('main/rank_list.html', users=users)

@bp.route('/contest_list/')
def contest_list():
    contests = Contest.query.order_by(Contest.start_time).all()
    return render_template('main/contest_list.html', contests=reversed(contests))

@bp.route('/user/<int:user_id>/')
def user_details(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    contest_list_json = user.gen_contest_list()
    return render_template('main/user.html', user=user, contest_list_json=contest_list_json, reversed=reversed)

@bp.route('/contest/<int:contest_id>/')
def contest_details(contest_id):
    contest = Contest.query.filter_by(id=contest_id).first_or_404()
    return render_template('main/contest.html', contest=contest, contestants=contest.contestants)

vj_rating/main/templates/main/contest.html
{% extends "base.html" %}
{% block page_content %}

<div class="main_bg card">
    <h1>{{ contest.name }}</h1>
    <p>
        Start time: {{ moment(contest.start_time).format('LLL') }} <br>
        End time: {{ moment(contest.end_time).format('LLL') }} <br>
        Duration: {{ moment(contest.end_time).duration_from(contest.start_time) }} <br>
        Participant count : {{ contest.participant_count }} <br>
        <a href="https://vjudge.net/contest/{{- contest.id }}">Source</a>
    </p>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Username</th>
                    <th>Solved</th>
                    <th>Penalty</th>
                    <th>Rating</th>
                    <th>Δ</th>
                </tr>
            </thead>
            <tbody>
                {% for c in contestants %}
                <tr>
                    <th>{{ c.rank }}</th>
                    <td id="user.{{ c.user.id }}"><a
                            href="{{ url_for('main.user_details', user_id=c.user.id) }}">{{ c.user.name }} <span
                            class="table-nickname">({{ c.user.nickname }})</span></a></td>
                    <td>{{ c.solved }}</td>
                    <td>{{ c.penalty }}</td>
                    {% if c.before_rating is none %}
                    <td>{{ c.after_rating }}</td>
                    {% else %}
                    <td>{{ c.before_rating }}→{{ c.after_rating }}</td>
                    {% endif %}
                    {% if c.before_rating is none %} <td>-</td>
                    {% else %}
                    {% if c.before_rating > c.after_rating %}<td style="color: red">
                        {% elif c.before_rating < c.after_rating -%}
                    <td style="color: green">+
                        {%- else %}
                    <td>
                        {%- endif %}
                        {{- c.after_rating - c.before_rating }}</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

vj_rating/main/templates/main/contest_list.html
{% extends "base.html" %} {% block page_content %}

<div class="main_bg card">
    <h1>Contest list</h1>
    <div class="table-responsive">
        <table class="table ">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Contest Name</th>
                    <th>Start Time</th>
                    <th>Duration</th>
                    <th>Participant Count</th>
                </tr>
            </thead>
            <tbody>
                {% for c in contests %}
                <tr>
                    <th>{{ c.id }}</th>
                    <td><a href="{{ url_for('main.contest_details', contest_id=c.id) }}">{{ c.name }}</a></td>
                    <td>{{ moment(c.start_time).format('LLL') }}</td>
                    <td>{{ moment(c.end_time).duration_from(c.start_time) }}</td>
                    <td>{{ c.participant_count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

vj_rating/main/templates/main/index.html
{% extends "base.html" %}

{% block page_content %}
<div class="jumbotron main_bg">
    <h1>Henuacm</h1>
    <p>On development.</p>
    <p><a class="btn btn-primary btn-lg" href="{{ url_for('main.rank_list') }}" role="button">Check it out!</a></p>
  </div>
{% endblock %}

vj_rating/main/templates/main/rank_list.html
{% extends "base.html" %}
{% block page_content %}

<div class="main_bg card">
    <h1>Rank list</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Username</th>
                    <th>Rating</th>
                </tr>
            </thead>
            <tbody>
                {% for u in users %}
                <tr>
                    <th>{{ u.rank }}</th>
                    <td><a href="{{ url_for('main.user_details', user_id=u.id)}}">{{ u.name }} <span
                                class="table-nickname">({{ u.nickname }})</span></a></td>
                    <td>{{ u.rating }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

vj_rating/main/templates/main/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="row">
    <div class="col-md-4">
        <div class="user_profile_card main_bg">
            <div id="user_profile_card_bg"></div>
            <div id="user_profile_card_content">
                <img id="user_profile_card_avatar" src="{{ url_for('static', filename='img/default.jpg') }}"
                    class="rounded-circle" />
                <div id="user_profile_card_name">
                    <div class="username">{{user.name}}</div>
                    <div class="nickname">{{user.nickname}}</div>
                </div>
                <ul class="numbers-summary user_profile_card_stats">
                    <li>
                        <div>Rank</div>
                        <div>{{ user.rank }}</div>
                    </li>
                    <li>
                        <div>Rating</div>
                        <div>{{ user.rating }}</div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div class="main_bg card">
            <h2>Contests</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Contest Name</th>
                            <th>Start Time</th>
                            <th>Rank</th>
                            <th>Rating</th>
                            <th>Δ</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in reversed(user.sorted_contestants) %}
                        <tr>
                            <td><a href="{{ url_for('main.contest_details', contest_id=c.contest.id) }}#user.{{- user.id }}">{{ c.contest.name }}</a></td>
                            <td>{{ moment(c.contest.start_time).format('LLL') }}</td>
                            <td>{{ c.rank }}</td>
                            {% if c.before_rating is none %}
                            <td>{{ c.after_rating }}</td>
                            {% else %}
                            <td>{{ c.before_rating }}→{{ c.after_rating }}</td>
                            {% endif %}
                            {% if c.before_rating is none %} <td>-</td>
                            {% else %}
                            {% if c.before_rating > c.after_rating %}<td style="color: red">
                                {% elif c.before_rating < c.after_rating -%}
                            <td style="color: green">+
                                {%- else %}
                            <td>
                                {%- endif %}
                                {{- c.after_rating - c.before_rating }}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="main_bg card">
            <div id="line_chart" style="width: 100%;height:400px;"></div>
        </div>

    </div>
</div>
{% endblock %}
{% block scripts %}
{{ super() }}
<!-- 引入 echarts.js -->
<script src="https://cdn.bootcss.com/echarts/4.2.1-rc1/echarts.min.js"></script>
<script>
    var data = JSON.parse('{{ contest_list_json|safe }}');
    var maxRating = Math.max.apply(null, data.map((x) => x.rating));
    var minRating = Math.min.apply(null, data.map((x) => x.rating));
    option = {
        baseOption: {
            title: {
                x: 'center',
                text: '{{ user.name }}\'s rating',
            },
            xAxis: {
                type: 'time',
            },
            yAxis: {
                max: Math.round(maxRating / 200 + 2) * 200,
                min: Math.max(Math.round(minRating / 200 - 2) * 200, 0)
            },
            dataset: {
                source: data
            },
            tooltip: {
                trigger: 'axis',
                formatter: function (params) {
                    //https://github.com/ecomfe/echarts/commit/86bcb9a87bcc568d7ef6427aba45ec105f0d0bee
                    var res = '';

                    params.forEach(v => {
                        var data = v.data;
                        res += `${echarts.format.getTooltipMarker(v.color)} ${data.name}<br>`
                        res += `${moment.utc(data.time).local().format('LLL')}<br>Rating:${data.rating}`;
                    });
                    return res;
                }
            },
            toolbox: {
                left: 'center',
                top:20,
                feature: {
                    dataZoom: {
                        yAxisIndex: 'none'
                    },
                    restore: {},
                    saveAsImage: {}
                }
            },
            series: [{
                name: 'Rating',
                type: 'line',
                markPoint: {
                    data: [
                        { type: 'max', name: '最大值' }
                    ]
                },
                encode: {
                    x: 'time',
                    y: 'rating'
                },
                markArea: {
                    silent: true,
                    data: [
                        [{
                            yAxis: 0,
                            itemStyle: { color: '#ccc' }
                        }, {
                            yAxis: 1199
                        }],
                        [{
                            yAxis: 1200,
                            itemStyle: { color: '#7f7' }
                        }, {
                            yAxis: 1399
                        }],
                        [{
                            yAxis: 1400,
                            itemStyle: { color: '#77ddbb' }
                        }, {
                            yAxis: 1599
                        }],
                        [{
                            yAxis: 1600,
                            itemStyle: { color: '#aaf' }
                        }, {
                            yAxis: 1899
                        }],
                        [{
                            yAxis: 1900,
                            itemStyle: { color: '#f8f' }
                        }, {
                            yAxis: 2199
                        }],
                        [{
                            yAxis: 2200,
                            itemStyle: { color: '#ffcc88' }
                        }, {
                            yAxis: 2299
                        }],
                        [{
                            yAxis: 2300,
                            itemStyle: { color: '#ffbb55' }
                        }, {
                            yAxis: 2399
                        }],
                        [{
                            yAxis: 2400,
                            itemStyle: { color: '#f77' }
                        }, {
                            yAxis: 2599
                        }],
                        [{
                            yAxis: 2600,
                            itemStyle: { color: '#f33' }
                        }, {
                            yAxis: 2899
                        }], [{
                            yAxis: 2900,
                            itemStyle: { color: '#ffcc88' }
                        }, {
                            yAxis: 9999
                        }]
                    ]
                }
            }],
        },
        media: [
            {
                query: { maxWidth: 550 },
                option: {
                    grid: {
                        left: 55
                    },
                }
            }
        ],

    };
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('line_chart'));

    window.onresize = function () {
        myChart.resize();
        // .resize后加括号哦，这里还可以写其他的事件
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>
{% endblock %}