vj_rating/blog/views.py
from flask import Blueprint, render_template
from sqlalchemy import desc

from .models import Post

bp = Blueprint('blog', __name__, url_prefix='/blog',
               template_folder='templates')

@bp.route('/')
def index():
    posts = Post.query.order_by(desc(Post.create_time)).all()
    return render_template('blog/index.html', posts=posts)

@bp.route('/<int:post_id>/')
def get_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    return render_template('blog/post.html', post=post)

vj_rating/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}HENUACM{% if subtitle %} - {{ subtitle }}{% endif %}{% endblock %}</title>
    {% block styles %}
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" , rel="stylesheet" />
    {% endblock %}
    {% block head %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    {% endblock %}
</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">HENUACM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('blog.index') }}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.rank_list') }}">Rank List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.contest_list') }}">Contest List</a>
                </li>
        </div>
    </nav>
    {% endblock %}

    {% block content %}
    <main class="container">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        {% block page_content %}
        {% endblock %}
    </main>
    {% endblock %}
    
    
    <footer class="body_footer">
            {% block footer %}
            All Copyright Reserved © 2008-{{ moment.current_year() }} HENU ACM team
            {% endblock %}
    </footer>
    

    {% block scripts %}
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {{ moment.include_moment() }}
    <script src="{{ url_for('static', filename='js/moment_duration_formatter.js') }}"></script>
    {% endblock %}
</body>

</html>